### ISSUE TITLE
Rename PBF file

### ISSUE THREAD

**Issue by dobriseb** [kartoza/docker-osm#102]
Hi,

Thanks you for this work.

At first start, my DB was desperately empty.
I've seen that dockerosm_osmupdate was executing this command :
`bash -c while [ ! -f /home/settings/country.pbf ] ; do sleep 1; done && python3 -u /home/download.py`

So, I have to rename my .PBF file to country.pbf for it to start to import data.

Is that the normal way to do it ?
If yes, why isn't it documented in the Readme.md ?

**Comment by NyakudyaA** [comment]
> Hi,
> 
> Thanks you for this work.
> 
> At first start, my DB was desperately empty.
> I've seen that dockerosm_osmupdate was executing this command :
> `bash -c while [ ! -f /home/settings/country.pbf ] ; do sleep 1; done && python3 -u /home/download.py`
> 
> So, I have to rename my .PBF file to country.pbf for it to start to import data.
> 
> Is that the normal way to do it ?
> If yes, why isn't it documented in the Readme.md ?

I will add it to the README, but if you have time please populate the readme with a PR

**Comment by NyakudyaA** [comment]
This has been done
