### ISSUE TITLE
dockerosm_db | 2020-09-29 03:45:02.007 UTC [1613] [unknown]@[unknown] LOG:  could not accept SSL connection: tlsv1 alert unknown ca

### ISSUE THREAD

**Issue by medivhliu** [kartoza/docker-osm#104]
I got SSL connection errors. How can i solve it

**Comment by NyakudyaA** [comment]
@medivhliu can you open a PR with kartoza/postgis as this relates more to the database

**Comment by markbaumgarten** [comment]
Same issue here. What do you mean with "can you open a PR" ?

medivhliu is asking a question: "How can I solve it?", but you are asking him/her/etc to provide the solution in a pull request?

I have the same question: How to solve this?

**Comment by NyakudyaA** [comment]
> Same issue here. What do you mean with "can you open a PR" ?
> 
> medivhliu is asking a question: "How can I solve it?", but you are asking him/her/etc to provide the solution in a pull request?
> 
> I have the same question: How to solve this?

@markbaumgarten it was a typo. I meant open an issue at https://github.com/kartoza/docker-postgis because the issue is more a docker-postgis issue rather than docker-osm

**Comment by NyakudyaA** [comment]
@markbaumgarten @medivhliu Can you please describe your setup and how you got the error so that I can investigate when I have a moment

**Comment by markbaumgarten** [comment]
I tried to follow my own path through the documentation. I only have a
single machine and want everything to run inside docker-compose.

So i did something like this:

mba@mba-ThinkPad-T450s:~/docker-osm$ docker-compose -f docker-compose.yml
-f docker-compose-web.yml up
Creating dockerosm_db ... done
Creating dockerosm_osmenrich   ... done
Creating dockerosm_imposm      ... done
Creating dockerosm_osmupdate   ... done
Creating dockerosm_martin      ... done
Creating docker-osm_pgadmin4_1 ... done
Creating dockerosm_qgisserver  ... done
Attaching to dockerosm_db, dockerosm_osmupdate, dockerosm_osmenrich,
dockerosm_imposm, docker-osm_pgadmin4_1, dockerosm_martin,
dockerosm_qgisserver
dockerosm_imposm | Detect SRID: 4326
dockerosm_imposm | Clip: no
dockerosm_imposm | QGIS style: yes
dockerosm_imposm | OSM PBF file: /home/settings/country.pbf
dockerosm_imposm | Mapping: /home/settings/country.pbf
dockerosm_imposm | No custom SQL files post-pbf-import.sql detected in
/home/settings
dockerosm_imposm | Geojson Initial Import Clip: /home/settings/clip.geojson
dockerosm_imposm | QGIS Style file: /home/settings/qgis_style.sql
dockerosm_imposm | Geojson for clipping: /home/settings/clip.geojson
dockerosm_imposm | The checkup is OK.
dockerosm_imposm | The database is not empty. Let's import only diff files.
dockerosm_imposm | Sleeping for 120 seconds.
dockerosm_db  | Add rule to pg_hba: 0.0.0.0/0
dockerosm_db  | Add rule to pg_hba: replication replicator
dockerosm_db  | Setup master database
dockerosm_db  | 2020-11-10 16:05:46.031 UTC [25] LOG:  starting PostgreSQL
12.2 (Debian 12.2-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc
(Debian 8.3.0-6) 8.3.0, 64-bit
dockerosm_db  | 2020-11-10 16:05:46.031 UTC [25] LOG:  listening on IPv4
address "127.0.0.1", port 5432
dockerosm_db  | 2020-11-10 16:05:46.042 UTC [25] LOG:  listening on Unix
socket "/var/run/postgresql/.s.PGSQL.5432"
dockerosm_db  | 2020-11-10 16:05:46.072 UTC [30] LOG:  database system was
interrupted; last known up at 2020-11-10 14:20:33 UTC
dockerosm_db  | 2020-11-10 16:05:46.110 UTC [37] postgres@postgres FATAL:
 the database system is starting up
dockerosm_db  | psql: error: could not connect to server: FATAL:  the
database system is starting up
dockerosm_db  | 2020-11-10 16:05:46.156 UTC [30] LOG:  database system was
not properly shut down; automatic recovery in progress
dockerosm_db  | 2020-11-10 16:05:46.166 UTC [30] LOG:  redo starts at
0/22AAAE0
dockerosm_db  | 2020-11-10 16:05:46.166 UTC [30] LOG:  invalid record
length at 0/22AB420: wanted 24, got 0
dockerosm_db  | 2020-11-10 16:05:46.166 UTC [30] LOG:  redo done at
0/22AB3E8
dockerosm_db  | 2020-11-10 16:05:46.199 UTC [25] LOG:  database system is
ready to accept connections
dockerosm_db  |                               List of databases
dockerosm_db  |    Name    |  Owner   | Encoding | Collate |  Ctype  |
Access privileges
dockerosm_db  |
-----------+----------+----------+---------+---------+-----------------------
dockerosm_db  |  gis       | docker   | UTF8     | C.UTF-8 | C.UTF-8 |
dockerosm_db  |  postgres  | postgres | UTF8     | C.UTF-8 | C.UTF-8 |
dockerosm_db  |  template0 | postgres | UTF8     | C.UTF-8 | C.UTF-8 |
=c/postgres          +
dockerosm_db  |            |          |          |         |         |
postgres=CTc/postgres
dockerosm_db  |  template1 | postgres | UTF8     | C.UTF-8 | C.UTF-8 |
=c/postgres          +
dockerosm_db  |            |          |          |         |         |
postgres=CTc/postgres
dockerosm_db  | (4 rows)
dockerosm_db  |
dockerosm_db  | postgres ready
dockerosm_db  | Setup postgres User:Password
dockerosm_db  | Creating superuser docker
dockerosm_db  | ALTER ROLE
dockerosm_db  | Creating replication user replicator
dockerosm_db  | ALTER ROLE
dockerosm_db  | gis db already exists
dockerosm_db  |                               List of databases
dockerosm_db  |    Name    |  Owner   | Encoding | Collate |  Ctype  |
Access privileges
dockerosm_db  |
-----------+----------+----------+---------+---------+-----------------------
dockerosm_db  |  gis       | docker   | UTF8     | C.UTF-8 | C.UTF-8 |
dockerosm_db  |  postgres  | postgres | UTF8     | C.UTF-8 | C.UTF-8 |
dockerosm_db  |  template0 | postgres | UTF8     | C.UTF-8 | C.UTF-8 |
=c/postgres          +
dockerosm_db  |            |          |          |         |         |
postgres=CTc/postgres
dockerosm_db  |  template1 | postgres | UTF8     | C.UTF-8 | C.UTF-8 |
=c/postgres          +
dockerosm_db  |            |          |          |         |         |
postgres=CTc/postgres
dockerosm_db  | (4 rows)
dockerosm_db  |
dockerosm_db  | 2020-11-10 16:05:47.618 UTC [25] LOG:  received smart
shutdown request
dockerosm_db  | 2020-11-10 16:05:47.624 UTC [25] LOG:  background worker
"logical replication launcher" (PID 44) exited with exit code 1
dockerosm_db  | 2020-11-10 16:05:47.624 UTC [39] LOG:  shutting down
dockerosm_db  | 2020-11-10 16:05:47.645 UTC [25] LOG:  database system is
shut down
dockerosm_db  | Postgres initialisation process completed .... restarting
in foreground
dockerosm_db  | 2020-11-10 16:05:48.651 UTC [137] LOG:  starting PostgreSQL
12.2 (Debian 12.2-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc
(Debian 8.3.0-6) 8.3.0, 64-bit
dockerosm_db  | 2020-11-10 16:05:48.651 UTC [137] LOG:  listening on IPv4
address "0.0.0.0", port 5432
dockerosm_db  | 2020-11-10 16:05:48.651 UTC [137] LOG:  listening on IPv6
address "::", port 5432
dockerosm_db  | 2020-11-10 16:05:48.655 UTC [137] LOG:  listening on Unix
socket "/var/run/postgresql/.s.PGSQL.5432"
dockerosm_db  | 2020-11-10 16:05:48.676 UTC [139] LOG:  database system was
shut down at 2020-11-10 16:05:47 UTC
dockerosm_db  | 2020-11-10 16:05:48.682 UTC [137] LOG:  database system is
ready to accept connections
dockerosm_db  | 2020-11-10 16:06:22.147 UTC [169] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:22.151 UTC [172] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:22.152 UTC [170] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:22.154 UTC [171] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:22.159 UTC [173] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:22.162 UTC [175] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:22.165 UTC [174] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:22.168 UTC [176] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:22.172 UTC [177] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:22.174 UTC [178] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_martin | [2020-11-10T16:06:22Z INFO  martin] Watch mode enabled
dockerosm_martin | [2020-11-10T16:06:22Z INFO  martin] Starting martin
v0.5.0
dockerosm_martin | [2020-11-10T16:06:22Z INFO  martin] Config is not set
dockerosm_martin | [2020-11-10T16:06:22Z INFO  martin] Connecting to
database
dockerosm_db  | 2020-11-10 16:06:22.178 UTC [179] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_osmenrich | Mapping: settings/mapping.yml
dockerosm_osmenrich | Load Mapping file data.
dockerosm_db  | 2020-11-10 16:06:22.179 UTC [180] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:22.184 UTC [181] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_osmupdate | OSM PBF file: /home/settings/country.pbf
dockerosm_osmupdate | The checkup is OK.
dockerosm_osmenrich | /home/enrich.py:170: YAMLLoadWarning: calling
yaml.load() without Loader=... is deprecated, as the default Loader is
unsafe. Please read https://msg.pyyaml.org/load for full details.
dockerosm_osmenrich |   mapping_data = yaml.load(document)
dockerosm_db  | 2020-11-10 16:06:22.188 UTC [183] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:22.195 UTC [184] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_osmenrich | The checkup is OK.
dockerosm_osmenrich | Run enrich process
dockerosm_db  | 2020-11-10 16:06:22.203 UTC [186] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_osmenrich | Enrich Database with empty changeset
dockerosm_osmenrich | Checking data from table osm_admin
dockerosm_db  | 2020-11-10 16:06:22.204 UTC [185] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:22.205 UTC [182] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_osmenrich | Checking data from table osm_aeroways
dockerosm_db  | 2020-11-10 16:06:22.215 UTC [188] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_osmenrich | Checking data from table osm_amenities
dockerosm_db  | 2020-11-10 16:06:22.216 UTC [187] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_osmenrich | Checking data from table osm_barrierpoints
dockerosm_osmupdate | Timestamp from the latest imported diff :
2020-11-10T14:25:13Z
dockerosm_osmupdate | Old time     : 2020-11-10T14:25:13Z
dockerosm_osmupdate | Current time : 2020-11-10T16:06:17Z
dockerosm_osmupdate | osmupdate -v --max-days=100 sporadic --max-merge=7
--compression-level=1 --base-url=
http://planet.openstreetmap.org/replication/ 2020-11-10T14:25:13Z
/home/import_queue/2020-11-10T14:25:13Z->-2020-11-10T16:06:17Z.osc.gz
dockerosm_osmupdate | osmupdate Parameter: --max-days=100
dockerosm_osmupdate | osmupdate Parameter: sporadic
dockerosm_osmupdate | osmupdate Parameter: --max-merge=7
dockerosm_osmupdate | osmupdate Parameter: --compression-level=1
dockerosm_osmupdate | osmupdate Parameter: --base-url=
http://planet.openstreetmap.org/replication/
dockerosm_osmupdate | osmupdate Parameter: 2020-11-10T14:25:13Z
dockerosm_osmenrich | Checking data from table osm_barrierways
dockerosm_db  | 2020-11-10 16:06:22.550 UTC [189] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_osmupdate | osmupdate Parameter:
/home/import_queue/2020-11-10T14:25:13Z->-2020-11-10T16:06:17Z.osc.gz
dockerosm_db  | 2020-11-10 16:06:22.556 UTC [191] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_osmenrich | Checking data from table osm_buildings
dockerosm_osmupdate | osmupdate: newest sporadic timestamp: (no timestamp)
dockerosm_osmenrich | Checking data from table osm_housenumbers
dockerosm_db  | 2020-11-10 16:06:22.558 UTC [190] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_osmenrich | Checking data from table osm_housenumbers_interpolated
dockerosm_osmenrich | Checking data from table osm_landusages
dockerosm_db  | 2020-11-10 16:06:22.562 UTC [192] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:22.565 UTC [193] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_osmenrich | Checking data from table osm_places
dockerosm_osmenrich | Checking data from table osm_roads
dockerosm_db  | 2020-11-10 16:06:22.569 UTC [194] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_osmenrich | Checking data from table osm_transport_areas
dockerosm_db  | 2020-11-10 16:06:22.574 UTC [195] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_osmupdate | osmupdate: newest minutely timestamp:
2020-11-10T16:06:04Z
dockerosm_osmenrich | Checking data from table osm_transport_points
dockerosm_osmenrich | Checking data from table osm_waterareas
dockerosm_osmenrich | Checking data from table osm_waterways
dockerosm_osmenrich | Enrich Database with diff file in import_done
dockerosm_osmenrich | Processing
2020-11-09T21:42:03Z->-2020-11-10T13:53:04Z.osc.gz
dockerosm_db  | 2020-11-10 16:06:22.579 UTC [197] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_osmupdate | osmupdate: newest hourly timestamp:
2020-11-10T16:00:00Z
dockerosm_db  | 2020-11-10 16:06:22.579 UTC [196] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:22.581 UTC [198] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_osmupdate | osmupdate: newest daily timestamp:
2020-11-10T00:00:00Z
dockerosm_osmupdate | osmupdate: minutely changefile 4277401: downloading
dockerosm_db  | 2020-11-10 16:06:22.588 UTC [200] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_osmupdate | osmupdate: minutely changefile 4277400:
2020-11-10T16:05:03Z
dockerosm_osmupdate | osmupdate: minutely changefile 4277400: downloading
dockerosm_osmupdate | osmupdate: minutely changefile 4277399:
2020-11-10T16:04:03Z
dockerosm_osmupdate | osmupdate: minutely changefile 4277399: downloading
dockerosm_db  | 2020-11-10 16:06:22.590 UTC [199] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:22.595 UTC [201] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:22.596 UTC [202] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:22.602 UTC [203] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:22.610 UTC [204] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:22.611 UTC [206] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:22.614 UTC [205] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:22.619 UTC [207] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:22.621 UTC [208] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:23.360 UTC [209] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:23.377 UTC [210] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:23.381 UTC [212] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:23.383 UTC [211] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:23.394 UTC [214] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:23.399 UTC [215] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:23.400 UTC [213] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:23.416 UTC [216] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:23.419 UTC [217] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:23.424 UTC [218] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:23.431 UTC [221] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:23.433 UTC [219] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:23.436 UTC [220] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:23.441 UTC [222] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:23.444 UTC [224] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:23.447 UTC [223] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:23.448 UTC [225] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:23.453 UTC [226] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:23.455 UTC [227] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:23.458 UTC [228] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_osmupdate | osmupdate: minutely changefile 4277398:
2020-11-10T16:03:03Z
dockerosm_osmupdate | osmupdate: minutely changefile 4277398: downloading
dockerosm_osmupdate | osmupdate: minutely changefile 4277397:
2020-11-10T16:02:03Z
dockerosm_osmupdate | osmupdate: minutely changefile 4277397: downloading
dockerosm_osmupdate | osmupdate: minutely changefile 4277396:
2020-11-10T16:01:03Z
dockerosm_osmupdate | osmupdate: minutely changefile 4277396: downloading
dockerosm_osmupdate | osmupdate: minutely changefile 4277395:
2020-11-10T16:00:03Z
dockerosm_osmupdate | osmupdate: minutely changefile 4277395: downloading
dockerosm_osmupdate | osmupdate: Merging changefiles.
dockerosm_osmupdate | osmupdate: minutely changefile 4277394:
2020-11-10T15:59:03Z
dockerosm_osmupdate | osmupdate: hourly changefile 71553: downloading
dockerosm_osmupdate | osmupdate: hourly changefile 71552:
2020-11-10T15:00:00Z
dockerosm_osmupdate | osmupdate: hourly changefile 71552: downloading
dockerosm_qgisserver | [Tue Nov 10 16:06:23.729224 2020] [env:warn] [pid
1:tid 140468287781824] AH01506: PassEnv variable _ was undefined
dockerosm_qgisserver | [Tue Nov 10 16:06:23.735294 2020] [env:warn] [pid
1:tid 140468287781824] AH01506: PassEnv variable _ was undefined
dockerosm_qgisserver | [Tue Nov 10 16:06:23.740160 2020] [mpm_event:notice]
[pid 1:tid 140468287781824] AH00489: Apache/2.4.29 (Ubuntu) mod_fcgid/2.3.9
configured -- resuming normal operations
dockerosm_qgisserver | [Tue Nov 10 16:06:23.740345 2020] [core:notice] [pid
1:tid 140468287781824] AH00094: Command line: 'apache2 -D FOREGROUND'
dockerosm_osmupdate | osmupdate: hourly changefile 71551:
2020-11-10T14:00:00Z
dockerosm_osmupdate | osmupdate: Merging changefiles.
pgadmin4_1    | [2020-11-10 16:06:24 +0000] [1] [INFO] Starting gunicorn
19.9.0
pgadmin4_1    | [2020-11-10 16:06:24 +0000] [1] [INFO] Listening at:
http://[::]:80
(1)
pgadmin4_1    | [2020-11-10 16:06:24 +0000] [1] [INFO] Using worker: threads
pgadmin4_1    | [2020-11-10 16:06:24 +0000] [18] [INFO] Booting worker with
pid: 18
dockerosm_db  | 2020-11-10 16:06:24.965 UTC [229] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:24.987 UTC [230] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:24.993 UTC [232] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:25.004 UTC [231] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:25.021 UTC [234] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:25.023 UTC [233] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:25.043 UTC [235] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:25.067 UTC [237] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:25.068 UTC [236] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:25.068 UTC [238] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:25.107 UTC [240] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:25.107 UTC [239] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:25.130 UTC [243] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:25.136 UTC [242] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:25.141 UTC [241] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:25.156 UTC [245] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:25.158 UTC [247] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:25.164 UTC [246] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:25.164 UTC [244] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:25.176 UTC [248] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_osmupdate | osmupdate: Creating output file.
dockerosm_osmupdate | osmupdate: Deleting temporary files.
dockerosm_osmupdate | osmupdate: Completed successfully.
dockerosm_osmupdate | Creating diff successful :
2020-11-10T14:25:13Z->-2020-11-10T16:06:17Z.osc.gz
dockerosm_osmupdate | Sleeping for 120 seconds.
dockerosm_db  | 2020-11-10 16:06:28.171 UTC [249] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:28.195 UTC [250] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:28.198 UTC [251] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:28.211 UTC [252] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:28.222 UTC [253] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:28.230 UTC [254] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:28.253 UTC [255] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:28.268 UTC [256] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:28.274 UTC [257] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:28.275 UTC [258] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:28.301 UTC [259] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:28.309 UTC [261] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:28.310 UTC [260] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:28.341 UTC [262] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca
dockerosm_db  | 2020-11-10 16:06:28.342 UTC [263] [unknown]@[unknown] LOG:
 could not accept SSL connection: tlsv1 alert unknown ca

**Comment by NyakudyaA** [comment]
@markbaumgarten i tried to run the docker-compose and I didn't get the error. Can you try to use the db image 13.0

**Comment by NyakudyaA** [comment]
Please open if the issue still exists
