### ISSUE TITLE
Exception in importer.py with mknod

### ISSUE THREAD

**Issue by bchartier** [kartoza/docker-osm#105]
Hi,
When I tested docker-osm I encountered an error with importer.py, more precisely with mknod function here:
https://github.com/kartoza/docker-osm/blob/develop/docker-imposm3/importer.py#L239
At runtime I got an exception telling me that mknod was not available.

I don't understand why this exception occured. I saw mknod was specific to Unix systems. I didn't investigate much on this. I fixed this by replacing mknod by pathlib.Path.touch.

I don't know if I missed some obvious configuration of the project. I can share my fix with a pull request if you like.

**Comment by NyakudyaA** [comment]
@bchartier you can do a PR if it will improve the default settings

**Comment by bchartier** [comment]
Done: see #107

**Comment by madsbertelsen** [comment]
I get a permission error on the mknod call:
```
dockerosm_imposm | Traceback (most recent call last):
dockerosm_imposm |   File "/home/importer.py", line 345, in <module>
dockerosm_imposm |     importer.run()
dockerosm_imposm |   File "/home/importer.py", line 255, in run
dockerosm_imposm |     self._first_pbf_import([])
dockerosm_imposm |   File "/home/importer.py", line 290, in _first_pbf_import
dockerosm_imposm |     self.lockfile()
dockerosm_imposm |   File "/home/importer.py", line 243, in lockfile
dockerosm_imposm |     mknod(setup_lockfile)
dockerosm_imposm | PermissionError: [Errno 1] Operation not permitted
```
It would be nice to get the PR merged.

**Comment by NyakudyaA** [comment]
@madsbertelsen I have merged this

**Comment by bchartier** [comment]
Thank you.
