### ISSUE TITLE
Pin dependencies

### ISSUE THREAD

**Issue by frafra** [kartoza/docker-osm#126]
Both #121 and #125 are errors generated from `requirements.txt` with non-pinned dependencies, thus producing unpredictable results.

**Comment by NyakudyaA** [comment]
Can we ping the dependencies like the one we have for https://github.com/kartoza/docker-osm/pull/134/files#diff-ab6e660ebff0d1195dcd31fb1c3f596e7ef980fdf2e19dd9566cc49c1c71b323 would you be willing to take this one @frafra

**Comment by frafra** [comment]
Sure, it is a good improvement.
