### ISSUE TITLE
Include some QGIS styles in the DB

### ISSUE THREAD

**Issue by Gustry** [kartoza/docker-osm#19]

**Comment by mayeulk** [comment]
Could this enhancement request be more specific? I understand it is related to rendering with QGIS. Since you wrote "in the DB", do you mean adding a field in a table to ease the use by QGIS? Or, create a QGIS style sheet? (but then, this is a flat file, not part of the DB)

**Comment by NyakudyaA** [comment]
Some default styles are already applied
