### ISSUE TITLE
Check if the clipping for diff works

### ISSUE THREAD

**Issue by Gustry** [kartoza/docker-osm#20]
OSM Update can't clip a diff file : http://wiki.openstreetmap.org/wiki/Osmconvert#Clipping_OSM_Change_Files.3F
So the poly file is useless ...

Like osmosis, we can run this kind of SQL script to delete everything outside a bbox or WKT : 
http://wiki.openstreetmap.org/wiki/User:Stephankn/knowledgebase#Cleanup_of_ways_outside_the_bounding_box

**Comment by Gustry** [comment]
OSM Update can't clip a diff file : http://wiki.openstreetmap.org/wiki/Osmconvert#Clipping_OSM_Change_Files.3F

**Comment by Gustry** [comment]
Work in progress : 
```
CREATE OR REPLACE FUNCTION clean_tables() RETURNS void AS $$
DECLARE osm_tables CURSOR FOR 
	SELECT table_name
	FROM information_schema.tables
	WHERE table_schema='public'
	AND table_type='BASE TABLE'
	AND table_name LIKE 'osm_%';
BEGIN
	FOR osm_table IN osm_tables LOOP
		EXECUTE 'DELETE FROM ' || quote_ident(osm_table.table_name) || ' USING clip WHERE ST_Disjoint(geom,geometry);';
	END LOOP;
END;
$$ LANGUAGE plpgsql;

select clean_tables();
```

**Comment by timlinux** [comment]
Maybe its not necessary these days but it might be worth checking if vacuuming the db after doing bulk deletes is a good idea.

**Comment by NyakudyaA** [comment]
Not useful now as imposm3 natively supports this. You can use a GeoJSON file to limit the geometries on import

**Comment by Gustry** [comment]
Do you mean you are going to make the clip shapefile deprecated and add the note about this new geojson file?

**Comment by NyakudyaA** [comment]
Hi @Gustry it is already deprecated and we have added it to the description 

https://github.com/kartoza/docker-osm#clipping
