### ISSUE TITLE
Create database management container

### ISSUE THREAD

**Issue by Gustry** [kartoza/docker-osm#27]
# Problem

Actually, there are 3 running containers : 
- database
- osmupdate
- imposm

osmupdate and imposm are both checking files at the beginning of the container and then waiting 45 seconds for the database to be ready. We should avoid checking twice.

Moreover, imposm is doing more work than importing PBF and diff files. This container is also importing QGIS styling at the beginning and running scheduled clipping.

![docker-osm](https://cloud.githubusercontent.com/assets/1609292/12032508/49cdca42-ae19-11e5-9480-c6bc24415323.png)
# Proposed solution

We may implement a kind of DB manager docker container.
This container will take care of : 
- import the clipping shapefile in the DB (shp2pgsql)
- import the QGIS styling in the DB (psql)
- Import the SQL custom triggers (psql)
- Run the clipping SQL function on a regular interval (psql)
- Vacuum #20 on a regular interval (psql)

We may add some process too : checking files ...

**Comment by timlinux** [comment]
Sounds like a good idea!

**Comment by Gustry** [comment]
Yes, it's even more important now since kartoza/postgis doesn't include shp2pgsql anymore since a few months. See https://github.com/kartoza/docker-osm/issues/49

**Comment by NyakudyaA** [comment]
This is now covered
