### ISSUE TITLE
running make_import causes an error

### ISSUE THREAD

**Issue by sindile** [kartoza/docker-osm#49]
when running make import_clip results in the following error
------------------------------------------------------------------
Importing clip shapefile
------------------------------------------------------------------
invalid command \":
ERROR:  syntax error at or near "rpc"
LINE 1: rpc error: code = 2 desc = oci runtime error: exec failed: c...

I did also check in the dockerosm_db container using "whereis shp2pgsql" no such file

Any ideas what could be wrong?

**Comment by Gustry** [comment]
I also noticed that `shp2pgsql`, needed to import the shapefile in the DB, is missing from the kartoza/docker-postgis image. It's related how postgis is installed. I'm looking at this issue, thanks for raising it.

**Comment by seabre** [comment]
I ran into this as well. As a tempory fix, you can modify the Makefile to use your local copy of shp2pgsql if you happen to have it installed.

**Comment by mayeulk** [comment]
Looking at [stackexchange](https://gis.stackexchange.com/questions/148524/i-have-not-found-shp2pgsql-in-postgis-installation)   it says
> When installing postgis on Linux, be sure to install the client also, as postgis on its own will not install the shp2pgsql executable

A quick fix is to login in the container and do:
````
apt-get update
apt-get install -y postgis
which shp2pgsql
````

The /settings folder is in imposm (see [code defining settings folder](https://github.com/kartoza/docker-osm/blob/b1a780088e0a660d3a32fb3f12f4454c14366cde/docker-compose.yml#L31) ), so as a quickfix I ran this in imposm container, but this adds a lot of software which presumably are already in the kartoza/postgis container

**Comment by Gustry** [comment]
This should be fixed with #72
