### ISSUE TITLE
allow using .poly file for clipping instead of .shp

### ISSUE THREAD

**Issue by mayeulk** [kartoza/docker-osm#61]
The documentation says: 

> You can put a shapefile in the clip folder. This shapefile will be used for clipping every features after the import. This file has to be named 'clip.shp'. When the database container is running, import the shapefile in the database using the command : 'make import_clip'.

However, it is often easier to get a .poly file that to produce a .shp file (out of a .poly). For instance, for South Africa, this is enough:
`wget https://download.geofabrik.de/africa/south-africa.poly`
It would be great to be able to use such a poly file. Looking rapidly at the code, it seems that it might be called anyway (unsure), see https://github.com/kartoza/docker-osm/blob/85b14edccebd71ecb00bc4023a3b39bf6244db66/docker-osmupdate/osmupdate.c#L81

**Comment by NyakudyaA** [comment]
@mayeulk clipping is based on the PostgreSQL table called clip. the most common way to import this is by running `make import-clip`. You can also mount a SQL script when starting the db container as explained here https://github.com/kartoza/docker-postgis#running-sql-scripts-on-container-startup. The question we should really be asking is how do we import `.poly` files into the PostgreSQL database using ogr2ogr. If you know the answer please provide it and we add the logic to check if `.poly` file exists

**Comment by NyakudyaA** [comment]
Imposm3 allows you to clip using GeoJSON.
