### ISSUE TITLE
names of containers are not consisistent

### ISSUE THREAD

**Issue by mayeulk** [kartoza/docker-osm#67]
https://github.com/kartoza/docker-osm/blob/b1a780088e0a660d3a32fb3f12f4454c14366cde/Makefile#L1

see also https://github.com/kartoza/docker-osm/issue_comments#issuecomment-411777356

In my setting (ubuntu 16.04), compared with the container names in this Makefile, mine have _1 at the end, such as:
```
dockerosm_db_1
dockerosm_imposm_1
dockerosm_osmupdate_1
```
Hence, many commands from the Makefile based on $(PROJECT_ID) do not work.

**Comment by mayeulk** [comment]
I could not find official documentation of why "_1" is added, but some useful discussions here and there:

https://github.com/docker/compose/issues/472
https://stackoverflow.com/questions/46446135/docker-compose-avoid-docker-containers-being-named-with-underscore

Also, possibly below, a solution? Use explicit naming and take advantages of labels?

https://github.com/docker/compose/issues/652#issuecomment-82620019

> Right now, Compose uses a naming convention (projectname_servicename_instance) in order to "identify" which containers belong to which project, because there are no other ways to do that.
> Now that labels are possible, labels can be used to "identify" the containers, without having to use a special naming.
> For example, by starting a container named foobar but adding some labels;
[> --label com.docker.compose.project=myproject
> --label com.docker.compose.service=web
> --label com.docker.compose.instance=1](url)
> With those labels, compose is able to determine that the container belongs to project myproject, that it is the container for the web service, and that it is the "first" (1) instance.

> The name of the container is no longer relevant and can be changed/customized without problems.
> Also docker supports filtering based on labels, so to find all containers belonging to a project, compose can use docker ps --filter label=com.docker.compose.project=myproject to find all containers belonging to project my project.

**Comment by Gustry** [comment]
This should be fixed in #70
