### ISSUE TITLE
SQL request are slow

### ISSUE THREAD

**Issue by 0live** [kartoza/docker-osm#78]
Hi guys,
I'm currently making some test for a world OSM database deployed by docker-osm (great work btw!) but i have a big issue: any sql request on database are very slow (several hours for a simple SELECT COUNT(osm_id) on public.osm_buildings e.g.).

I created a DB on the same PostGIS instance running under Docker, and for a same request on a table where i imported 2.7 millions buildings, i takes around 7 seconds.

On each table, "osm_id" and "geometry" fields are indexed, so i don't understand why it takes so many times.

**Comment by Gustry** [comment]
You have the same database (with same extent) and running in docker, it's strange indeed.
Which docker base image are you using for the database?

If it's the same image, what happen if you stop osmupdate and imposm containers?

Did you check `docker inspect` command about your 3 postgis database?

I'm just giving some ideas where to check.

**Comment by 0live** [comment]
Thanks for you answer, so:
FYI I'm not the who installed the databased, i resume this project.
"Which docker base image are you using for the database?" -> It seems running on docker-osm-20181009_db_1 according to Portainer

**Comment by NyakudyaA** [comment]
@0live You can use a tool like https://pgtune.leopard.in.ua/#/ to check the hardware configurations against the postgresql conf files and adjust accordingly. Also please ensure that you use the latest image for PostGIS always as it is always optimized better but the settings are more generic ie to someone having a 4gig ram, 2 CPU etc. Also, periodically run `vacuum full;` on the database
