### ISSUE TITLE
Alllow multiple .pbf files in settings and import them all

### ISSUE THREAD

**Issue by amenk** [kartoza/docker-osm#79]
Looks like only the first one is imported.

Importing settings/* would be great

**Comment by amenk** [comment]
we you accept a pull requests, allowing several regions / countries to be bootstrapped?

**Comment by NyakudyaA** [comment]
Yes, pull requests are encouraged to improve functionality

**Comment by amenk** [comment]
Cool :) unfortunately I realized the imposm does not easily support openstreetmap-carto and I might switch to using https://github.com/Overv/openstreetmap-tile-server instead ...

we'll see

**Comment by NyakudyaA** [comment]
@amenk I think this can be easily solved by importing a continent and then you include the shapefile for clipping to cover the specific countries or areas you intend to work on. Unless there is a tool to combine pbf to a single one ?.
**NB** be mindful of the space issue when importing a continent
