### ISSUE TITLE
Error while spinning up the project

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-osm#8]
imposm_1    | [Jul 30 20:43:29] [INFO] Imposm took: 56.593014789s
imposm_1    | Sleeping for 120 seconds.
imposm_1    | Traceback (most recent call last):
imposm_1    |   File "/home/importer.py", line 166, in <module>
imposm_1    |     sleep(default['TIME'])
imposm_1    | TypeError: a float is required
dockerosm_imposm_1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
Stopping dockerosm_osmupdate_1...
Stopping dockerosm_db_1...

**Comment by Gustry** [comment]
This bug has already been fixed.
