### ISSUE TITLE
Minimal OL browser with search

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-osm#93]
We would like to have a small demo app on top of docker osm with these features:

* Uses Postgrest on top of docker-osm
* Adds a js static page displaying default OL tiles
* add a button with will put the mouse in 'identify mode'
* add a small search box widget. The widget will ask you to enter first one street name, then another.

# Identify

* Add a tool that enables clicking on the map
* When clicking on the map, a Postgrest query should be run and a JSON structure returned containing:
 * town, 
 * region, 
 *country

For demo purposes, these should be displayed in a nice message overlay on the map

# Street search

Two modes:

## Mode 1: Single Street

* Type a name (partial or complete) and receive a list of matches (first 10 perhaps)
* Type ahead completion after entering the first three chars
* Select a name
* Zoom to the selected street
* Highlight the selected road (draw an overlay as GeoJSON)

## Mode 2: Street Intersection

* Type a name (partial or complete) and receive a list of matches (first 10 perhaps)
* Type ahead completion after entering the first three chars
* Select a name
* In a second box, type a name (partial or complete) and receive a list of matches filtered to roads that intersect the first road
* Select the second name
* Zoom to the intersection of the two streets
* Highlight the two relevant streets (draw as an overlay from GeoJSON)

I propose to implement the above as:

* New docker container 'docker-osm-viewer' contianing the static OL map page pointing at GeoServer
* Postgrest for street and name API
* mappings.yaml to include town, region, country admin boundaries from OSM

Please chat with me if yoo prefer another approach.

Note that we can't use public web services like nominatum for this since the whole deployment needs to be able to work in a LAN disconnected from the internet if needed.

**Comment by timlinux** [comment]
For the first use case:

![image](https://user-images.githubusercontent.com/178003/73157985-89f7fb80-40da-11ea-8eb1-588b3146e462.png)

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/73158576-240c7380-40dc-11ea-8256-e1acd297d393.png)

**Comment by meomancer** [comment]
hi @Tim @mazano 

i already done the identifying administrative
but i'm using administrative from osm (which is using admin_level, it doesn't specify settlement, region, country)
how do i parse to these format from osm data? or do we have data specifically for that?

![Selection_057](https://user-images.githubusercontent.com/4530905/73165407-4f1bb500-4126-11ea-8181-467072ea4673.png)

**Comment by Gustry** [comment]
Do you want a mapping between OSM admin_level and names?
Maybe https://github.com/inasafe/inasafe/blob/develop/safe/resources/osm/admin_level_per_country.json ?

**Comment by timlinux** [comment]
Behaviour for street search

![Screenshot 2020-01-27 at 15 21 08](https://user-images.githubusercontent.com/178003/73187074-b29ee600-4118-11ea-9972-5ed168256df8.png)

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/73187925-0d850d00-411a-11ea-9eed-e59a36856d63.png)

**Comment by timlinux** [comment]
@meomancer hopefully those wireframes give you some idea of the expected user experience....implementation details can differ. Main emphasis should be on the API, though client might like to use your JS examples.

**Comment by meomancer** [comment]
ok @timlinux 

thank you @Gustry 
i will use that mapping json

**Comment by NyakudyaA** [comment]
This is implemented in https://github.com/kartoza/docker-osm-examples/tree/master/archive/street-search
